
fprintf('R2L')
new = size(strmatch('xlock.',testset.label),1) ...
    + size(strmatch('snmpgetattack.',testset.label),1) ...
    + size(strmatch('httptunnel.',testset.label),1) ...
    + size(strmatch('named.',testset.label),1) ...
    + size(strmatch('sendmail.',testset.label),1) ...
    + size(strmatch('snmpguess.',testset.label),1) ...
    + size(strmatch('worm.',testset.label),1) ...
    + size(strmatch('xsnoop.',testset.label),1)

old = size(strmatch('ftp_write.',testset.label),1) ...
    + size(strmatch('guess_passwd.',testset.label),1) ...
    + size(strmatch('imap.',testset.label),1) ...
    + size(strmatch('multihop.',testset.label),1) ...
    + size(strmatch('phf.',testset.label),1) ...
    + size(strmatch('spy.',testset.label),1) ...
    + size(strmatch('warezclient.',testset.label),1) ...
    + size(strmatch('warezmaster.',testset.label),1) ...
    
new + old

fprintf('PROBE')
new = size(strmatch('mscan.',testset.label),1) ...
    + size(strmatch('saint.',testset.label),1) 

old = size(strmatch('ipsweep.',testset.label),1) ...
    + size(strmatch('nmap.',testset.label),1) ...
    + size(strmatch('portsweep.',testset.label),1) ...
    + size(strmatch('satan.',testset.label),1) 

new + old

fprintf('DOS')
new = size(strmatch('udpstorm.',testset.label),1) ...
    + size(strmatch('apache2.',testset.label),1) ...
    + size(strmatch('mailbomb.',testset.label),1) ...
    + size(strmatch('processtable.',testset.label),1)

old = size(strmatch('back.',testset.label),1) ...
    + size(strmatch('land.',testset.label),1) ...
    + size(strmatch('neptune.',testset.label),1) ...
    + size(strmatch('pod.',testset.label),1) ...
    + size(strmatch('smurf.',testset.label),1) ...
    + size(strmatch('teardrop.',testset.label),1)

new + old

